version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      microsoft:
        patterns: ["Microsoft.*", "System.*"]
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      mantine:
        patterns: ["@mantine/*"]
      tanstack:
        patterns: ["@tanstack/*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
