/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/wanted/missing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PagingResourceOfSongResource"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wanted/cutoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PagingResourceOfSongResource"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemResource"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/task": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskResource"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/task/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskResource"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/soulseek/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SoulseekSettingsResource"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SoulseekSettingsUpdateResource"];
                    "application/*+json": components["schemas"]["SoulseekSettingsUpdateResource"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SoulseekSettingsUpdateResponseResource"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/soulseek/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SoulseekStatusResource"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArtistResource"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artist/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArtistResource"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    deezerId?: number | string;
                    isrc?: string;
                    songId?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PreviewResource"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/song": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    artistId?: number | string;
                    monitored?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PagingResourceOfSongResource"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SongAddResource"];
                    "application/*+json": components["schemas"]["SongAddResource"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SongResource"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/song/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SongResource"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SongUpdateResource"];
                    "application/*+json": components["schemas"]["SongUpdateResource"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SongResource"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/song/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SongLookupRequest"];
                    "application/*+json": components["schemas"]["SongLookupRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SongLookupResource"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/song/{id}/albumcontexts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlbumOptionResource"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/song/{id}/albumcontext": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SongAlbumContextUpdateResource"];
                    "application/*+json": components["schemas"]["SongAlbumContextUpdateResource"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SongResource"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LibraryResource"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LibraryResource"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LibraryResource"];
                    "application/*+json": components["schemas"]["LibraryResource"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LibraryResource"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qualitydefinition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QualityDefinitionResource"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qualityprofile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QualityProfileResource"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QualityProfileResource"];
                    "application/*+json": components["schemas"]["QualityProfileResource"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QualityProfileResource"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qualityprofile/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QualityProfileResource"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QualityProfileResource"];
                    "application/*+json": components["schemas"]["QualityProfileResource"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QualityProfileResource"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        patch?: never;
        trace?: never;
    };
    "/api/v1/song/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BulkAddResource"];
                    "application/*+json": components["schemas"]["BulkAddResource"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BulkAddAcceptedResource"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/importlist/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportListResource"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/importlistitem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    importListId?: number | string;
                    state?: components["schemas"]["ImportListItemState"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PagingResourceOfImportListItemResource"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/importlistitem/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImportListItemResolveResource"];
                    "application/*+json": components["schemas"]["ImportListItemResolveResource"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportListItemResource"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/importlistitem/{id}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportListItemResource"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PagingResourceOfHistoryResource"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    refresh?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResource"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JsonElement"];
                    "application/*+json": components["schemas"]["JsonElement"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/command/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResource"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blocklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PagingResourceOfBlocklistResource"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blocklist/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    loginFailed?: boolean;
                    returnUrl?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    returnUrl?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        Username?: string;
                        Password?: string;
                        RememberMe?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthUserResource"];
                        "application/json": components["schemas"]["AuthUserResource"];
                        "text/json": components["schemas"]["AuthUserResource"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAuthUserResource"];
                    "text/json": components["schemas"]["UpdateAuthUserResource"];
                    "application/*+json": components["schemas"]["UpdateAuthUserResource"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AlbumContextKind: number;
        AlbumOptionResource: {
            key: string;
            mbReleaseId: null | string;
            mbReleaseGroupId: null | string;
            title: string;
            albumArtist: string;
            primaryType: null | string;
            secondaryTypes: string[];
            status: null | string;
            date: null | string;
            /** Format: int32 */
            trackNo: null | number | string;
            /** Format: int32 */
            totalTracks: null | number | string;
            isCurrent: boolean;
        };
        AlbumPolicy: number;
        ArtistResource: {
            /** Format: int64 */
            id: number | string;
            name: string;
            sortName: string;
            mbArtistId: null | string;
            /** Format: int64 */
            deezerId: null | number | string;
            /** Format: int32 */
            songCount: number | string;
        };
        AuthUserResource: {
            configured: boolean;
            username: null | string;
        };
        AuthenticationMethod: number;
        BlocklistResource: {
            /** Format: int64 */
            id: number | string;
            /** Format: int64 */
            songId: null | number | string;
            sourceType: string;
            blocklistKey: string;
            reason: string;
            /** Format: date-time */
            date: string;
            /** Format: date-time */
            expiresAt: null | string;
        };
        BulkAddAcceptedResource: {
            /** Format: int64 */
            importListId: number | string;
            /** Format: int64 */
            commandId: number | string;
            /** Format: int32 */
            lineCount: number | string;
        };
        BulkAddResource: {
            text: null | string;
            /** Format: int64 */
            qualityProfileId: null | number | string;
            /** Format: int64 */
            libraryId: null | number | string;
        };
        CommandResource: {
            /** Format: int64 */
            id: number | string;
            name: string;
            commandName: string;
            message: null | string;
            body: null | string;
            priority: string;
            status: components["schemas"]["CommandStatus"];
            result: components["schemas"]["CommandResult"];
            /** Format: date-time */
            queued: string;
            /** Format: date-time */
            started: null | string;
            /** Format: date-time */
            ended: null | string;
            duration: null | string;
            exception: null | string;
            trigger: components["schemas"]["CommandTrigger"];
            /** Format: date-time */
            stateChangeTime: null | string;
        };
        CommandResult: number;
        CommandStatus: number;
        CommandTrigger: number;
        HistoryEventType: number;
        HistoryResource: {
            /** Format: int64 */
            id: number | string;
            /** Format: int64 */
            songId: number | string;
            song: components["schemas"]["SongResource"];
            eventType: components["schemas"]["HistoryEventType"];
            /** Format: date-time */
            date: string;
            /** Format: int64 */
            sourceInstanceId: null | number | string;
            /** Format: int64 */
            qualityId: null | number | string;
            data: components["schemas"]["JsonElement"];
        };
        ImportListCandidate: {
            source: string;
            mbRecordingId: null | string;
            /** Format: int64 */
            deezerId: null | number | string;
            title: string;
            artistCredit: string;
            /** Format: int32 */
            durationMs: null | number | string;
            /** Format: double */
            score: number | string;
        };
        ImportListCountsResource: {
            /** Format: int32 */
            pending: number | string;
            /** Format: int32 */
            added: number | string;
            /** Format: int32 */
            unresolved: number | string;
            /** Format: int32 */
            skipped: number | string;
        };
        ImportListItemResolveResource: {
            mbRecordingId: null | string;
            /** Format: int64 */
            deezerId: null | number | string;
        };
        ImportListItemResource: {
            /** Format: int64 */
            id: number | string;
            /** Format: int64 */
            importListId: number | string;
            /** Format: int32 */
            line: number | string;
            text: string;
            artist: null | string;
            title: null | string;
            state: components["schemas"]["ImportListItemState"];
            reason: null | string;
            /** Format: int64 */
            songId: null | number | string;
            candidates: components["schemas"]["ImportListCandidate"][];
        };
        ImportListItemState: number;
        ImportListResource: {
            /** Format: int64 */
            id: number | string;
            type: string;
            name: string;
            /** Format: date-time */
            created: string;
            /** Format: date-time */
            lastSyncedAt: null | string;
            counts: components["schemas"]["ImportListCountsResource"];
        };
        JsonElement: unknown;
        LibraryLayout: number;
        LibraryResource: {
            /** Format: int64 */
            id: number | string;
            name: string;
            rootPath: string;
            layout: components["schemas"]["LibraryLayout"];
            namingTemplate: string;
            sidecarOptions: components["schemas"]["JsonElement"];
            albumPolicy: components["schemas"]["AlbumPolicy"];
            /** Format: int32 */
            minTracksPerRealAlbum: number | string;
            plexSectionId: null | string;
            isDefault: boolean;
        };
        PagingResourceOfBlocklistResource: {
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            sortKey: string;
            sortDirection: string;
            /** Format: int32 */
            totalRecords: number | string;
            records: components["schemas"]["BlocklistResource"][];
        };
        PagingResourceOfHistoryResource: {
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            sortKey: string;
            sortDirection: string;
            /** Format: int32 */
            totalRecords: number | string;
            records: components["schemas"]["HistoryResource"][];
        };
        PagingResourceOfImportListItemResource: {
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            sortKey: string;
            sortDirection: string;
            /** Format: int32 */
            totalRecords: number | string;
            records: components["schemas"]["ImportListItemResource"][];
        };
        PagingResourceOfSongResource: {
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            sortKey: string;
            sortDirection: string;
            /** Format: int32 */
            totalRecords: number | string;
            records: components["schemas"]["SongResource"][];
        };
        PreviewResource: {
            url: string;
        };
        QualityDefinitionResource: {
            /** Format: int64 */
            id: number | string;
            name: string;
            group: string;
            /** Format: int32 */
            rank: number | string;
            codec: string;
            lossless: boolean;
            /** Format: int32 */
            minBitrate: null | number | string;
            /** Format: int32 */
            maxBitrate: null | number | string;
            /** Format: int32 */
            bitDepth: null | number | string;
        };
        QualityProfileItemResource: {
            name: null | string;
            qualities: components["schemas"]["QualityProfileQualityResource"][];
            allowed: boolean;
        };
        QualityProfileQualityResource: {
            /** Format: int64 */
            id: number | string;
            name: null | string;
        };
        QualityProfileResource: {
            /** Format: int64 */
            id: number | string;
            name: string;
            upgradeAllowed: boolean;
            /** Format: int64 */
            cutoff: number | string;
            /** Format: int32 */
            minScore: number | string;
            /** Format: int32 */
            durationToleranceMs: number | string;
            items: components["schemas"]["QualityProfileItemResource"][];
        };
        SongAddResource: {
            mbRecordingId: null | string;
            /** Format: int64 */
            deezerId: null | number | string;
            /** Format: int64 */
            qualityProfileId: null | number | string;
            /** Format: int64 */
            libraryId: null | number | string;
            monitored: null | boolean;
        };
        SongAlbumContextResource: {
            kind: components["schemas"]["AlbumContextKind"];
            albumTitle: string;
            albumArtist: string;
            albumKey: string;
            mbReleaseId: null | string;
            mbReleaseGroupId: null | string;
            /** Format: int32 */
            trackNo: null | number | string;
            /** Format: int32 */
            discNo: null | number | string;
            /** Format: int32 */
            totalTracks: null | number | string;
            date: null | string;
            originalDate: null | string;
            coverUrl: null | string;
            isVariousArtists: boolean;
        };
        SongAlbumContextUpdateResource: {
            albumKey: null | string;
        };
        SongLookupRequest: {
            term: null | string;
        };
        SongLookupResource: {
            source: string;
            mbRecordingId: null | string;
            /** Format: int64 */
            deezerId: null | number | string;
            title: string;
            artistCredit: string;
            /** Format: int32 */
            durationMs: null | number | string;
            disambiguation: null | string;
            versionFlags: string[];
            firstReleaseDate: null | string;
            releaseTypes: string[];
            albumTitle: null | string;
            coverUrl: null | string;
            isrcs: string[];
            /** Format: double */
            score: number | string;
            viaIsrc: boolean;
            /** Format: int64 */
            existingSongId: null | number | string;
        };
        SongResource: {
            /** Format: int64 */
            id: number | string;
            title: string;
            artistCredit: string;
            /** Format: int64 */
            primaryArtistId: number | string;
            primaryArtistName: string;
            mbRecordingId: null | string;
            /** Format: int64 */
            deezerId: null | number | string;
            isrcs: string[];
            /** Format: int32 */
            durationMs: null | number | string;
            versionFlags: string[];
            monitored: boolean;
            /** Format: int64 */
            qualityProfileId: number | string;
            /** Format: int64 */
            libraryId: number | string;
            addedBy: string;
            /** Format: date-time */
            added: string;
            hasFile: boolean;
            /** Format: int64 */
            qualityId: null | number | string;
            albumContext: null | components["schemas"]["SongAlbumContextResource"];
        };
        SongUpdateResource: {
            monitored: null | boolean;
            /** Format: int64 */
            qualityProfileId: null | number | string;
        };
        SoulseekSearchBudgetResource: {
            /** Format: int32 */
            submittedInWindow: number | string;
            /** Format: int32 */
            maxSearches: number | string;
            /** Format: int32 */
            outstanding: number | string;
            /** Format: int32 */
            maxOutstanding: number | string;
            /** Format: date-time */
            nextAllowedAt: null | string;
        };
        SoulseekSettingsResource: {
            username: null | string;
            passwordSet: boolean;
            /** Format: int32 */
            listenPort: number | string;
            shareLibrary: boolean;
            sharedFolders: string[];
            /** Format: int32 */
            uploadSlots: number | string;
            /** Format: int32 */
            uploadSpeedLimitKib: number | string;
            distributedNetwork: boolean;
            downloadsDir: string;
            incompleteDir: string;
            readOnlyFields: string[];
        };
        SoulseekSettingsUpdateResource: {
            username?: null | string;
            password?: null | string;
            /** Format: int32 */
            listenPort?: null | number | string;
            shareLibrary?: null | boolean;
            sharedFolders?: null | string[];
            /** Format: int32 */
            uploadSlots?: null | number | string;
            /** Format: int32 */
            uploadSpeedLimitKib?: null | number | string;
            distributedNetwork?: null | boolean;
            downloadsDir?: null | string;
            incompleteDir?: null | string;
        };
        SoulseekSettingsUpdateResponseResource: {
            settings: components["schemas"]["SoulseekSettingsResource"];
            restartsSlskd: boolean;
        };
        SoulseekSharingResource: {
            enabled: boolean;
            folders: string[];
            /** Format: int32 */
            directories: null | number | string;
            /** Format: int32 */
            files: null | number | string;
        };
        SoulseekStatusResource: {
            mode: string;
            state: string;
            version: null | string;
            loggedIn: boolean;
            username: null | string;
            loginProblem: null | string;
            lastError: null | string;
            pendingRestart: boolean;
            sharing: components["schemas"]["SoulseekSharingResource"];
            searchBudget: components["schemas"]["SoulseekSearchBudgetResource"];
        };
        SystemResource: {
            appName: string;
            instanceName: string;
            version: string;
            /** Format: date-time */
            buildTime: string;
            isDebug: boolean;
            isProduction: boolean;
            isAdmin: boolean;
            isUserInteractive: boolean;
            startupPath: string;
            appData: string;
            osName: string;
            osVersion: string;
            isNetCore: boolean;
            isLinux: boolean;
            isOsx: boolean;
            isWindows: boolean;
            isDocker: boolean;
            isContainerized: boolean;
            mode: string;
            branch: string;
            authentication: components["schemas"]["AuthenticationMethod"];
            databaseType: string;
            databaseVersion: string;
            /** Format: int32 */
            migrationVersion: number | string;
            urlBase: string;
            runtimeVersion: string;
            runtimeName: string;
            /** Format: date-time */
            startTime: string;
            packageVersion: string;
            packageAuthor: string;
            packageUpdateMechanism: string;
        };
        TaskResource: {
            /** Format: int64 */
            id: number | string;
            name: string;
            taskName: string;
            /** Format: int32 */
            interval: number | string;
            /** Format: date-time */
            lastExecution: null | string;
            /** Format: date-time */
            lastStartTime: null | string;
            /** Format: date-time */
            nextExecution: null | string;
            lastDuration: string;
            lastResult: null | string;
        };
        UpdateAuthUserResource: {
            username: null | string;
            password: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
