// <auto-generated />
using System;
using Compilarr.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Compilarr.Core.Persistence.Migrations
{
    [DbContext(typeof(CompilarrDbContext))]
    [Migration("20260928105203_AddMetadataCache")]
    partial class AddMetadataCache
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Compilarr.Core.Domain.AlbumContext", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AlbumArtist")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("album_artist");

                    b.Property<string>("AlbumKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("album_key");

                    b.Property<string>("AlbumTitle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("album_title");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("cover_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<int?>("DiscNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("disc_no");

                    b.Property<bool>("IsVariousArtists")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_various_artists");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("MbReleaseGroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("mb_release_group_id");

                    b.Property<string>("MbReleaseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("mb_release_id");

                    b.Property<string>("OriginalDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_date");

                    b.Property<long>("SongId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("song_id");

                    b.Property<bool>("Sticky")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sticky");

                    b.Property<int?>("TotalTracks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_tracks");

                    b.Property<int?>("TrackNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("track_no");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_album_context");

                    b.HasIndex("AlbumKey")
                        .HasDatabaseName("ix_album_context_album_key");

                    b.HasIndex("SongId")
                        .IsUnique()
                        .HasDatabaseName("ix_album_context_song_id");

                    b.ToTable("album_context", (string)null);
                });

            modelBuilder.Entity("Compilarr.Core.Domain.Artist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long?>("DeezerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deezer_id");

                    b.Property<string>("MbArtistId")
                        .HasColumnType("TEXT")
                        .HasColumnName("mb_artist_id");

                    b.Property<int?>("MonitoredTopN")
                        .HasColumnType("INTEGER")
                        .HasColumnName("monitored_top_n");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SortName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sort_name");

                    b.Property<string>("SpotifyId")
                        .HasColumnType("TEXT")
                        .HasColumnName("spotify_id");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_artist");

                    b.HasIndex("MbArtistId")
                        .IsUnique()
                        .HasDatabaseName("ix_artist_mb_artist_id");

                    b.ToTable("artist", (string)null);
                });

            modelBuilder.Entity("Compilarr.Core.Domain.Library", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AlbumPolicy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("album_policy");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_default");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("layout");

                    b.Property<int>("MinTracksPerRealAlbum")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_tracks_per_real_album");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NamingTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("naming_template");

                    b.Property<string>("PlexSectionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("plex_section_id");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("root_path");

                    b.Property<string>("SidecarOptions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}")
                        .HasColumnName("sidecar_options");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_library");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_library_name");

                    b.ToTable("library", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AlbumPolicy = "FewestAlbums",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefault = true,
                            Layout = "Plexamp",
                            MinTracksPerRealAlbum = 2,
                            Name = "Music",
                            NamingTemplate = "{Album Artist Name}/{Album Title}/{medium:0}{track:00} - {Track Title}",
                            RootPath = "/data/music",
                            SidecarOptions = "{}",
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Compilarr.Core.Domain.Quality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("BitDepth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bit_depth");

                    b.Property<string>("Codec")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("codec");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group");

                    b.Property<bool>("Lossless")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lossless");

                    b.Property<int?>("MaxBitrate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_bitrate");

                    b.Property<int?>("MinBitrate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_bitrate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rank");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_quality");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_quality_name");

                    b.ToTable("quality", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Codec = "unknown",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Unknown",
                            Lossless = false,
                            Name = "Unknown",
                            Rank = 1,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2L,
                            Codec = "mp3",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Trash lossy",
                            Lossless = false,
                            MaxBitrate = 8,
                            MinBitrate = 8,
                            Name = "MP3-8",
                            Rank = 2,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3L,
                            Codec = "mp3",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Trash lossy",
                            Lossless = false,
                            MaxBitrate = 16,
                            MinBitrate = 16,
                            Name = "MP3-16",
                            Rank = 2,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4L,
                            Codec = "mp3",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Trash lossy",
                            Lossless = false,
                            MaxBitrate = 24,
                            MinBitrate = 24,
                            Name = "MP3-24",
                            Rank = 2,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5L,
                            Codec = "mp3",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Trash lossy",
                            Lossless = false,
                            MaxBitrate = 32,
                            MinBitrate = 32,
                            Name = "MP3-32",
                            Rank = 2,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6L,
                            Codec = "mp3",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Trash lossy",
                            Lossless = false,
                            MaxBitrate = 40,
                            MinBitrate = 40,
                            Name = "MP3-40",
                            Rank = 2,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7L,
                            Codec = "mp3",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Trash lossy",
                            Lossless = false,
                            MaxBitrate = 48,
                            MinBitrate = 48,
                            Name = "MP3-48",
                            Rank = 2,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8L,
                            Codec = "mp3",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Trash lossy",
                            Lossless = false,
                            MaxBitrate = 56,
                            MinBitrate = 56,
                            Name = "MP3-56",
                            Rank = 2,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9L,
                            Codec = "mp3",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Trash lossy",
                            Lossless = false,
                            MaxBitrate = 64,
                            MinBitrate = 64,
                            Name = "MP3-64",
                            Rank = 2,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10L,
                            Codec = "mp3",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Trash lossy",
                            Lossless = false,
                            MaxBitrate = 80,
                            MinBitrate = 80,
                            Name = "MP3-80",
                            Rank = 2,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11L,
                            Codec = "mp3",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Poor lossy",
                            Lossless = false,
                            MaxBitrate = 96,
                            MinBitrate = 96,
                            Name = "MP3-96",
                            Rank = 3,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12L,
                            Codec = "mp3",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Poor lossy",
                            Lossless = false,
                            MaxBitrate = 112,
                            MinBitrate = 112,
                            Name = "MP3-112",
                            Rank = 3,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13L,
                            Codec = "mp3",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Poor lossy",
                            Lossless = false,
                            MaxBitrate = 128,
                            MinBitrate = 128,
                            Name = "MP3-128",
                            Rank = 3,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14L,
                            Codec = "mp3",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Poor lossy",
                            Lossless = false,
                            MaxBitrate = 160,
                            MinBitrate = 160,
                            Name = "MP3-160",
                            Rank = 3,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15L,
                            Codec = "vorbis",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Poor lossy",
                            Lossless = false,
                            MaxBitrate = 180,
                            MinBitrate = 140,
                            Name = "Vorbis Q5",
                            Rank = 3,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16L,
                            Codec = "opus",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Poor lossy",
                            Lossless = false,
                            MaxBitrate = 112,
                            MinBitrate = 80,
                            Name = "OPUS-96",
                            Rank = 3,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17L,
                            Codec = "mp3",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Low lossy",
                            Lossless = false,
                            MaxBitrate = 192,
                            MinBitrate = 192,
                            Name = "MP3-192",
                            Rank = 4,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18L,
                            Codec = "mp3",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Low lossy",
                            Lossless = false,
                            MaxBitrate = 224,
                            MinBitrate = 224,
                            Name = "MP3-224",
                            Rank = 4,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19L,
                            Codec = "aac",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Low lossy",
                            Lossless = false,
                            MaxBitrate = 192,
                            MinBitrate = 192,
                            Name = "AAC-192",
                            Rank = 4,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20L,
                            Codec = "vorbis",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Low lossy",
                            Lossless = false,
                            MaxBitrate = 210,
                            MinBitrate = 180,
                            Name = "Vorbis Q6",
                            Rank = 4,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21L,
                            Codec = "wma",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Low lossy",
                            Lossless = false,
                            Name = "WMA",
                            Rank = 4,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22L,
                            Codec = "opus",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Low lossy",
                            Lossless = false,
                            MaxBitrate = 144,
                            MinBitrate = 112,
                            Name = "OPUS-128",
                            Rank = 4,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23L,
                            Codec = "mp3",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Mid lossy",
                            Lossless = false,
                            MaxBitrate = 256,
                            MinBitrate = 256,
                            Name = "MP3-256",
                            Rank = 5,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24L,
                            Codec = "mp3",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Mid lossy",
                            Lossless = false,
                            MaxBitrate = 250,
                            MinBitrate = 170,
                            Name = "MP3-VBR-V2",
                            Rank = 5,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25L,
                            Codec = "aac",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Mid lossy",
                            Lossless = false,
                            MaxBitrate = 256,
                            MinBitrate = 256,
                            Name = "AAC-256",
                            Rank = 5,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26L,
                            Codec = "vorbis",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Mid lossy",
                            Lossless = false,
                            MaxBitrate = 240,
                            MinBitrate = 210,
                            Name = "Vorbis Q7",
                            Rank = 5,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27L,
                            Codec = "vorbis",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Mid lossy",
                            Lossless = false,
                            MaxBitrate = 280,
                            MinBitrate = 240,
                            Name = "Vorbis Q8",
                            Rank = 5,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 28L,
                            Codec = "opus",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Mid lossy",
                            Lossless = false,
                            MaxBitrate = 176,
                            MinBitrate = 144,
                            Name = "OPUS-160",
                            Rank = 5,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 29L,
                            Codec = "mp3",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "High lossy",
                            Lossless = false,
                            MaxBitrate = 320,
                            MinBitrate = 320,
                            Name = "MP3-320",
                            Rank = 6,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 30L,
                            Codec = "mp3",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "High lossy",
                            Lossless = false,
                            MaxBitrate = 320,
                            MinBitrate = 220,
                            Name = "MP3-VBR-V0",
                            Rank = 6,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 31L,
                            Codec = "aac",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "High lossy",
                            Lossless = false,
                            MaxBitrate = 320,
                            MinBitrate = 320,
                            Name = "AAC-320",
                            Rank = 6,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 32L,
                            Codec = "aac",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "High lossy",
                            Lossless = false,
                            Name = "AAC-VBR",
                            Rank = 6,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 33L,
                            Codec = "vorbis",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "High lossy",
                            Lossless = false,
                            MaxBitrate = 340,
                            MinBitrate = 280,
                            Name = "Vorbis Q9",
                            Rank = 6,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 34L,
                            Codec = "vorbis",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "High lossy",
                            Lossless = false,
                            MaxBitrate = 500,
                            MinBitrate = 340,
                            Name = "Vorbis Q10",
                            Rank = 6,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 35L,
                            Codec = "opus",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "High lossy",
                            Lossless = false,
                            MaxBitrate = 510,
                            MinBitrate = 176,
                            Name = "OPUS-192+",
                            Rank = 6,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 36L,
                            BitDepth = 16,
                            Codec = "flac",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Lossless",
                            Lossless = true,
                            Name = "FLAC",
                            Rank = 7,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 37L,
                            BitDepth = 16,
                            Codec = "alac",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Lossless",
                            Lossless = true,
                            Name = "ALAC",
                            Rank = 7,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 38L,
                            Codec = "ape",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Lossless",
                            Lossless = true,
                            Name = "APE",
                            Rank = 7,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 39L,
                            Codec = "wavpack",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Lossless",
                            Lossless = true,
                            Name = "WavPack",
                            Rank = 7,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 40L,
                            BitDepth = 24,
                            Codec = "flac",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Hi-res lossless",
                            Lossless = true,
                            Name = "FLAC 24-bit",
                            Rank = 8,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 41L,
                            BitDepth = 24,
                            Codec = "alac",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Hi-res lossless",
                            Lossless = true,
                            Name = "ALAC 24-bit",
                            Rank = 8,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 42L,
                            Codec = "wav",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Uncompressed",
                            Lossless = true,
                            Name = "WAV",
                            Rank = 9,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 43L,
                            Codec = "aiff",
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Uncompressed",
                            Lossless = true,
                            Name = "AIFF",
                            Rank = 9,
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Compilarr.Core.Domain.QualityProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long>("CutoffQualityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cutoff_quality_id");

                    b.Property<int>("DurationToleranceMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_tolerance_ms");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("items");

                    b.Property<int>("MinScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_score");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UpgradeAllowed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("upgrade_allowed");

                    b.HasKey("Id")
                        .HasName("pk_quality_profile");

                    b.HasIndex("CutoffQualityId")
                        .HasDatabaseName("ix_quality_profile_cutoff_quality_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_quality_profile_name");

                    b.ToTable("quality_profile", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CutoffQualityId = 29L,
                            DurationToleranceMs = 3000,
                            Items = "[{\"name\":null,\"qualityIds\":[1],\"allowed\":false},{\"name\":null,\"qualityIds\":[2,3,4,5,6,7,8,9,10],\"allowed\":false},{\"name\":null,\"qualityIds\":[11,12,13,14,15,16],\"allowed\":false},{\"name\":\"Low lossy\",\"qualityIds\":[17,18,19,22],\"allowed\":true},{\"name\":null,\"qualityIds\":[20,21],\"allowed\":false},{\"name\":\"Mid lossy\",\"qualityIds\":[23,24,28],\"allowed\":true},{\"name\":null,\"qualityIds\":[26,27],\"allowed\":false},{\"name\":\"High lossy\",\"qualityIds\":[29,30,25,31,32],\"allowed\":true},{\"name\":null,\"qualityIds\":[33,34,35],\"allowed\":false},{\"name\":\"Lossless\",\"qualityIds\":[36,37],\"allowed\":true},{\"name\":null,\"qualityIds\":[38,39],\"allowed\":false},{\"name\":\"Hi-res lossless\",\"qualityIds\":[40,41],\"allowed\":true},{\"name\":null,\"qualityIds\":[42,43],\"allowed\":false}]",
                            MinScore = 0,
                            Name = "Standard 320",
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpgradeAllowed = true
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CutoffQualityId = 36L,
                            DurationToleranceMs = 3000,
                            Items = "[{\"name\":null,\"qualityIds\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28],\"allowed\":false},{\"name\":\"High lossy\",\"qualityIds\":[29,30,31],\"allowed\":true},{\"name\":null,\"qualityIds\":[32,33,34,35],\"allowed\":false},{\"name\":\"Lossless\",\"qualityIds\":[36,37],\"allowed\":true},{\"name\":null,\"qualityIds\":[38,39],\"allowed\":false},{\"name\":\"Hi-res lossless\",\"qualityIds\":[40,41],\"allowed\":true},{\"name\":null,\"qualityIds\":[42,43],\"allowed\":false}]",
                            MinScore = 0,
                            Name = "Lossless",
                            UpdatedAt = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpgradeAllowed = true
                        });
                });

            modelBuilder.Entity("Compilarr.Core.Domain.Song", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("added_by");

                    b.Property<string>("ArtistCredit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("artist_credit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long?>("DeezerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deezer_id");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.PrimitiveCollection<string>("Isrcs")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("isrcs");

                    b.Property<long>("LibraryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("library_id");

                    b.Property<string>("MbRecordingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("mb_recording_id");

                    b.Property<string>("MbWorkId")
                        .HasColumnType("TEXT")
                        .HasColumnName("mb_work_id");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER")
                        .HasColumnName("monitored");

                    b.Property<long>("PrimaryArtistId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("primary_artist_id");

                    b.Property<long>("QualityProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality_profile_id");

                    b.Property<long?>("SourceProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_profile_id");

                    b.Property<string>("SpotifyId")
                        .HasColumnType("TEXT")
                        .HasColumnName("spotify_id");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.PrimitiveCollection<string>("VersionFlags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("version_flags");

                    b.Property<string>("YtmVideoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ytm_video_id");

                    b.HasKey("Id")
                        .HasName("pk_song");

                    b.HasIndex("DeezerId")
                        .IsUnique()
                        .HasDatabaseName("ix_song_deezer_id");

                    b.HasIndex("LibraryId")
                        .HasDatabaseName("ix_song_library_id");

                    b.HasIndex("MbRecordingId")
                        .IsUnique()
                        .HasDatabaseName("ix_song_mb_recording_id");

                    b.HasIndex("PrimaryArtistId")
                        .HasDatabaseName("ix_song_primary_artist_id");

                    b.HasIndex("QualityProfileId")
                        .HasDatabaseName("ix_song_quality_profile_id");

                    b.ToTable("song", (string)null);
                });

            modelBuilder.Entity("Compilarr.Core.Domain.SongArtist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("ArtistId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("artist_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<long>("SongId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("song_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_song_artist");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_song_artist_artist_id");

                    b.HasIndex("SongId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_song_artist_song_id_position");

                    b.ToTable("song_artist", (string)null);
                });

            modelBuilder.Entity("Compilarr.Core.Domain.SongFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AcoustId")
                        .HasColumnType("TEXT")
                        .HasColumnName("acoust_id");

                    b.Property<int?>("BitDepth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bit_depth");

                    b.Property<int?>("BitrateKbps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bitrate_kbps");

                    b.Property<int?>("Channels")
                        .HasColumnType("INTEGER")
                        .HasColumnName("channels");

                    b.Property<string>("Codec")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("codec");

                    b.Property<string>("Container")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("container");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<bool>("FingerprintVerified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fingerprint_verified");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("imported_at");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<long>("QualityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quality_id");

                    b.Property<int?>("SampleRate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sample_rate");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size");

                    b.Property<long>("SongId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("song_id");

                    b.Property<string>("SourceRef")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_ref");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.Property<string>("TagsWritten")
                        .HasColumnType("TEXT")
                        .HasColumnName("tags_written");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_song_file");

                    b.HasIndex("QualityId")
                        .HasDatabaseName("ix_song_file_quality_id");

                    b.HasIndex("SongId")
                        .IsUnique()
                        .HasDatabaseName("ix_song_file_song_id");

                    b.ToTable("song_file", (string)null);
                });

            modelBuilder.Entity("Compilarr.Core.Jobs.CommandRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ended_at");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT")
                        .HasColumnName("exception");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("queued_at");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("result");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_command");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_command_name");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_command_status");

                    b.ToTable("command", (string)null);
                });

            modelBuilder.Entity("Compilarr.Core.Metadata.MetadataCacheEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("fetched_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_metadata_cache");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_metadata_cache_expires_at");

                    b.HasIndex("Provider", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_metadata_cache_provider_key");

                    b.ToTable("metadata_cache", (string)null);
                });

            modelBuilder.Entity("Compilarr.Core.Persistence.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<TimeSpan?>("Interval")
                        .HasColumnType("TEXT")
                        .HasColumnName("interval");

                    b.Property<string>("LastResult")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_result");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_run_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_run_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_job");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_job_name");

                    b.ToTable("job", (string)null);
                });

            modelBuilder.Entity("Compilarr.Core.Persistence.Setting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_setting");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_setting_key");

                    b.ToTable("setting", (string)null);
                });

            modelBuilder.Entity("Compilarr.Core.Domain.AlbumContext", b =>
                {
                    b.HasOne("Compilarr.Core.Domain.Song", "Song")
                        .WithOne("AlbumContext")
                        .HasForeignKey("Compilarr.Core.Domain.AlbumContext", "SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_album_context_song_song_id");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Compilarr.Core.Domain.QualityProfile", b =>
                {
                    b.HasOne("Compilarr.Core.Domain.Quality", "CutoffQuality")
                        .WithMany()
                        .HasForeignKey("CutoffQualityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quality_profile_quality_cutoff_quality_id");

                    b.Navigation("CutoffQuality");
                });

            modelBuilder.Entity("Compilarr.Core.Domain.Song", b =>
                {
                    b.HasOne("Compilarr.Core.Domain.Library", null)
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_song_libraries_library_id");

                    b.HasOne("Compilarr.Core.Domain.Artist", "PrimaryArtist")
                        .WithMany()
                        .HasForeignKey("PrimaryArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_song_artist_primary_artist_id");

                    b.HasOne("Compilarr.Core.Domain.QualityProfile", null)
                        .WithMany()
                        .HasForeignKey("QualityProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_song_quality_profiles_quality_profile_id");

                    b.Navigation("PrimaryArtist");
                });

            modelBuilder.Entity("Compilarr.Core.Domain.SongArtist", b =>
                {
                    b.HasOne("Compilarr.Core.Domain.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_song_artist_artist_artist_id");

                    b.HasOne("Compilarr.Core.Domain.Song", "Song")
                        .WithMany("Artists")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_song_artist_song_song_id");

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Compilarr.Core.Domain.SongFile", b =>
                {
                    b.HasOne("Compilarr.Core.Domain.Quality", "Quality")
                        .WithMany()
                        .HasForeignKey("QualityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_song_file_qualities_quality_id");

                    b.HasOne("Compilarr.Core.Domain.Song", "Song")
                        .WithOne("File")
                        .HasForeignKey("Compilarr.Core.Domain.SongFile", "SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_song_file_song_song_id");

                    b.Navigation("Quality");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Compilarr.Core.Domain.Song", b =>
                {
                    b.Navigation("AlbumContext");

                    b.Navigation("Artists");

                    b.Navigation("File");
                });
#pragma warning restore 612, 618
        }
    }
}
