<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Compilarr.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Compilarr.Core\Compilarr.Core.csproj" />
    <ProjectReference Include="..\Compilarr.Sources.Slskd\Compilarr.Sources.Slskd.csproj" />
    <ProjectReference Include="..\Compilarr.Sources.Torznab\Compilarr.Sources.Torznab.csproj" />
    <ProjectReference Include="..\Compilarr.Sources.YouTube\Compilarr.Sources.YouTube.csproj" />
  </ItemGroup>

</Project>
